name:                glitter-sky
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/glitter-sky#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - http-types >= 0.12.1 && < 0.13
  - http-client >= 0.5.13 && < 0.6
  - http-client-tls >= 0.3.5 && < 0.4
  - bytestring >= 0.10.8 && < 0.11
  - containers >= 0.5.10 && < 0.6
  - safe
  - directory
  - filepath

executables:
  glitter-sky:
    source-dirs:      src
    main:             Main.hs
